[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.package]
authors = ["Rust for Web <info@rustforweb.org>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/RustForWeb/dom"

[workspace.dependencies]
web-sys = "0.3.69"
