use std::{collections::HashMap, str::FromStr};

#[derive(Debug, PartialEq, Eq)]
pub struct UnknownRoleError;

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaAbstractRole {
    Command,
    Composite,
    Input,
    Landmark,
    Range,
    Roletype,
    Section,
    Sectionhead,
    Select,
    Structure,
    Widget,
    Window,
}

impl FromStr for AriaAbstractRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "command" => Ok(AriaAbstractRole::Command),
            "composite" => Ok(AriaAbstractRole::Composite),
            "input" => Ok(AriaAbstractRole::Input),
            "landmark" => Ok(AriaAbstractRole::Landmark),
            "range" => Ok(AriaAbstractRole::Range),
            "roletype" => Ok(AriaAbstractRole::Roletype),
            "section" => Ok(AriaAbstractRole::Section),
            "sectionhead" => Ok(AriaAbstractRole::Sectionhead),
            "select" => Ok(AriaAbstractRole::Select),
            "structure" => Ok(AriaAbstractRole::Structure),
            "widget" => Ok(AriaAbstractRole::Widget),
            "window" => Ok(AriaAbstractRole::Window),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaWidgetRole {
    Button,
    Checkbox,
    Gridcell,
    Link,
    Menuitem,
    Menuitemcheckbox,
    Menuitemradio,
    Option,
    Progressbar,
    Radio,
    Scrollbar,
    Searchbox,
    Slider,
    Spinbutton,
    Switch,
    Tab,
    Tabpanel,
    Textbox,
    Treeitem,
}

impl FromStr for AriaWidgetRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "button" => Ok(AriaWidgetRole::Button),
            "checkbox" => Ok(AriaWidgetRole::Checkbox),
            "gridcell" => Ok(AriaWidgetRole::Gridcell),
            "link" => Ok(AriaWidgetRole::Link),
            "menuitem" => Ok(AriaWidgetRole::Menuitem),
            "menuitemcheckbox" => Ok(AriaWidgetRole::Menuitemcheckbox),
            "menuitemradio" => Ok(AriaWidgetRole::Menuitemradio),
            "option" => Ok(AriaWidgetRole::Option),
            "progressbar" => Ok(AriaWidgetRole::Progressbar),
            "radio" => Ok(AriaWidgetRole::Radio),
            "scrollbar" => Ok(AriaWidgetRole::Scrollbar),
            "searchbox" => Ok(AriaWidgetRole::Searchbox),
            "slider" => Ok(AriaWidgetRole::Slider),
            "spinbutton" => Ok(AriaWidgetRole::Spinbutton),
            "switch" => Ok(AriaWidgetRole::Switch),
            "tab" => Ok(AriaWidgetRole::Tab),
            "tabpanel" => Ok(AriaWidgetRole::Tabpanel),
            "textbox" => Ok(AriaWidgetRole::Textbox),
            "treeitem" => Ok(AriaWidgetRole::Treeitem),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaCompositeWidgetRole {
    Combobox,
    Grid,
    Listbox,
    Menu,
    Menubar,
    Radiogroup,
    Tablist,
    Tree,
    Treegrid,
}

impl FromStr for AriaCompositeWidgetRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "combobox" => Ok(AriaCompositeWidgetRole::Combobox),
            "grid" => Ok(AriaCompositeWidgetRole::Grid),
            "listbox" => Ok(AriaCompositeWidgetRole::Listbox),
            "menu" => Ok(AriaCompositeWidgetRole::Menu),
            "menubar" => Ok(AriaCompositeWidgetRole::Menubar),
            "radiogroup" => Ok(AriaCompositeWidgetRole::Radiogroup),
            "tablist" => Ok(AriaCompositeWidgetRole::Tablist),
            "tree" => Ok(AriaCompositeWidgetRole::Tree),
            "treegrid" => Ok(AriaCompositeWidgetRole::Treegrid),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaDocumentStructureRole {
    Application,
    Article,
    Blockquote,
    Caption,
    Cell,
    Columnheader,
    Definition,
    Deletion,
    Directory,
    Document,
    Emphasis,
    Feed,
    Figure,
    Generic,
    Group,
    Heading,
    Img,
    Insertion,
    List,
    Listitem,
    Mark,
    Math,
    Meter,
    None,
    Note,
    Paragraph,
    Presentation,
    Row,
    Rowgroup,
    Rowheader,
    Separator,
    Strong,
    Subscript,
    Superscript,
    Table,
    Term,
    Time,
    Toolbar,
    Tooltip,
}

impl FromStr for AriaDocumentStructureRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "application" => Ok(AriaDocumentStructureRole::Application),
            "article" => Ok(AriaDocumentStructureRole::Article),
            "blockquote" => Ok(AriaDocumentStructureRole::Blockquote),
            "caption" => Ok(AriaDocumentStructureRole::Caption),
            "cell" => Ok(AriaDocumentStructureRole::Cell),
            "columnheader" => Ok(AriaDocumentStructureRole::Columnheader),
            "definition" => Ok(AriaDocumentStructureRole::Definition),
            "deletion" => Ok(AriaDocumentStructureRole::Deletion),
            "directory" => Ok(AriaDocumentStructureRole::Directory),
            "document" => Ok(AriaDocumentStructureRole::Document),
            "emphasis" => Ok(AriaDocumentStructureRole::Emphasis),
            "feed" => Ok(AriaDocumentStructureRole::Feed),
            "figure" => Ok(AriaDocumentStructureRole::Figure),
            "generic" => Ok(AriaDocumentStructureRole::Generic),
            "group" => Ok(AriaDocumentStructureRole::Group),
            "heading" => Ok(AriaDocumentStructureRole::Heading),
            "img" => Ok(AriaDocumentStructureRole::Img),
            "insertion" => Ok(AriaDocumentStructureRole::Insertion),
            "list" => Ok(AriaDocumentStructureRole::List),
            "listitem" => Ok(AriaDocumentStructureRole::Listitem),
            "mark" => Ok(AriaDocumentStructureRole::Mark),
            "math" => Ok(AriaDocumentStructureRole::Math),
            "meter" => Ok(AriaDocumentStructureRole::Meter),
            "none" => Ok(AriaDocumentStructureRole::None),
            "note" => Ok(AriaDocumentStructureRole::Note),
            "paragraph" => Ok(AriaDocumentStructureRole::Paragraph),
            "presentation" => Ok(AriaDocumentStructureRole::Presentation),
            "row" => Ok(AriaDocumentStructureRole::Row),
            "rowgroup" => Ok(AriaDocumentStructureRole::Rowgroup),
            "rowheader" => Ok(AriaDocumentStructureRole::Rowheader),
            "separator" => Ok(AriaDocumentStructureRole::Separator),
            "strong" => Ok(AriaDocumentStructureRole::Strong),
            "subscript" => Ok(AriaDocumentStructureRole::Subscript),
            "superscript" => Ok(AriaDocumentStructureRole::Superscript),
            "table" => Ok(AriaDocumentStructureRole::Table),
            "term" => Ok(AriaDocumentStructureRole::Term),
            "time" => Ok(AriaDocumentStructureRole::Time),
            "toolbar" => Ok(AriaDocumentStructureRole::Toolbar),
            "tooltip" => Ok(AriaDocumentStructureRole::Tooltip),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaLandmarkRole {
    Banner,
    Complementary,
    Contentinfo,
    Form,
    Main,
    Navigation,
    Region,
    Search,
}

impl FromStr for AriaLandmarkRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "banner" => Ok(AriaLandmarkRole::Banner),
            "complementary" => Ok(AriaLandmarkRole::Complementary),
            "contentinfo" => Ok(AriaLandmarkRole::Contentinfo),
            "form" => Ok(AriaLandmarkRole::Form),
            "main" => Ok(AriaLandmarkRole::Main),
            "navigation" => Ok(AriaLandmarkRole::Navigation),
            "region" => Ok(AriaLandmarkRole::Region),
            "search" => Ok(AriaLandmarkRole::Search),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaLiveRegionRole {
    Alert,
    Log,
    Marquee,
    Status,
    Timer,
}

impl FromStr for AriaLiveRegionRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "alert" => Ok(AriaLiveRegionRole::Alert),
            "log" => Ok(AriaLiveRegionRole::Log),
            "marquee" => Ok(AriaLiveRegionRole::Marquee),
            "status" => Ok(AriaLiveRegionRole::Status),
            "timer" => Ok(AriaLiveRegionRole::Timer),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaWindowRole {
    Alertdialog,
    Dialog,
}

impl FromStr for AriaWindowRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "alertdialog" => Ok(AriaWindowRole::Alertdialog),
            "dialog" => Ok(AriaWindowRole::Dialog),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaUncategorizedRole {
    Code,
}

impl FromStr for AriaUncategorizedRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "code" => Ok(AriaUncategorizedRole::Code),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaDpubRole {
    DocAbstract,
    DocAcknowledgments,
    DocAfterword,
    DocAppendix,
    DocBacklink,
    DocBiblioentry,
    DocBibliography,
    DocBiblioref,
    DocChapter,
    DocColophon,
    DocConclusion,
    DocCover,
    DocCredit,
    DocCredits,
    DocDedication,
    DocEndnote,
    DocEndnotes,
    DocEpigraph,
    DocEpilogue,
    DocErrata,
    DocExample,
    DocFootnote,
    DocForeword,
    DocGlossary,
    DocGlossref,
    DocIndex,
    DocIntroduction,
    DocNoteref,
    DocNotice,
    DocPagebreak,
    DocPageheader,
    DocPagefooter,
    DocPagelist,
    DocPart,
    DocPreface,
    DocPrologue,
    DocPullquote,
    DocQna,
    DocSubtitle,
    DocTip,
    DocToc,
}

impl FromStr for AriaDpubRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "doc-abstract" => Ok(AriaDpubRole::DocAbstract),
            "doc-acknowledgments" => Ok(AriaDpubRole::DocAcknowledgments),
            "doc-afterword" => Ok(AriaDpubRole::DocAfterword),
            "doc-appendix" => Ok(AriaDpubRole::DocAppendix),
            "doc-backlink" => Ok(AriaDpubRole::DocBacklink),
            "doc-biblioentry" => Ok(AriaDpubRole::DocBiblioentry),
            "doc-bibliography" => Ok(AriaDpubRole::DocBibliography),
            "doc-biblioref" => Ok(AriaDpubRole::DocBiblioref),
            "doc-chapter" => Ok(AriaDpubRole::DocChapter),
            "doc-colophon" => Ok(AriaDpubRole::DocColophon),
            "doc-conclusion" => Ok(AriaDpubRole::DocConclusion),
            "doc-cover" => Ok(AriaDpubRole::DocCover),
            "doc-credit" => Ok(AriaDpubRole::DocCredit),
            "doc-credits" => Ok(AriaDpubRole::DocCredits),
            "doc-dedication" => Ok(AriaDpubRole::DocDedication),
            "doc-endnote" => Ok(AriaDpubRole::DocEndnote),
            "doc-endnotes" => Ok(AriaDpubRole::DocEndnotes),
            "doc-epigraph" => Ok(AriaDpubRole::DocEpigraph),
            "doc-epilogue" => Ok(AriaDpubRole::DocEpilogue),
            "doc-errata" => Ok(AriaDpubRole::DocErrata),
            "doc-example" => Ok(AriaDpubRole::DocExample),
            "doc-footnote" => Ok(AriaDpubRole::DocFootnote),
            "doc-foreword" => Ok(AriaDpubRole::DocForeword),
            "doc-glossary" => Ok(AriaDpubRole::DocGlossary),
            "doc-glossref" => Ok(AriaDpubRole::DocGlossref),
            "doc-index" => Ok(AriaDpubRole::DocIndex),
            "doc-introduction" => Ok(AriaDpubRole::DocIntroduction),
            "doc-noteref" => Ok(AriaDpubRole::DocNoteref),
            "doc-notice" => Ok(AriaDpubRole::DocNotice),
            "doc-pagebreak" => Ok(AriaDpubRole::DocPagebreak),
            "doc-pageheader" => Ok(AriaDpubRole::DocPageheader),
            "doc-pagefooter" => Ok(AriaDpubRole::DocPagefooter),
            "doc-pagelist" => Ok(AriaDpubRole::DocPagelist),
            "doc-part" => Ok(AriaDpubRole::DocPart),
            "doc-preface" => Ok(AriaDpubRole::DocPreface),
            "doc-prologue" => Ok(AriaDpubRole::DocPrologue),
            "doc-pullquote" => Ok(AriaDpubRole::DocPullquote),
            "doc-qna" => Ok(AriaDpubRole::DocQna),
            "doc-subtitle" => Ok(AriaDpubRole::DocSubtitle),
            "doc-tip" => Ok(AriaDpubRole::DocTip),
            "doc-toc" => Ok(AriaDpubRole::DocToc),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaGraphicsRole {
    GraphicsDocument,
    GraphicsObject,
    GraphicsSymbol,
}

impl FromStr for AriaGraphicsRole {
    type Err = UnknownRoleError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "graphics-document" => Ok(AriaGraphicsRole::GraphicsDocument),
            "graphics-object" => Ok(AriaGraphicsRole::GraphicsObject),
            "graphics-symbol" => Ok(AriaGraphicsRole::GraphicsSymbol),
            _ => Err(UnknownRoleError),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaRole {
    Alert,
    Alertdialog,
    Application,
    Article,
    Banner,
    Blockquote,
    Button,
    Caption,
    Cell,
    Checkbox,
    Code,
    Columnheader,
    Combobox,
    Complementary,
    Contentinfo,
    Definition,
    Deletion,
    Dialog,
    Directory,
    DocAbstract,
    DocAcknowledgments,
    DocAfterword,
    DocAppendix,
    DocBacklink,
    DocBiblioentry,
    DocBibliography,
    DocBiblioref,
    DocChapter,
    DocColophon,
    DocConclusion,
    DocCover,
    DocCredit,
    DocCredits,
    DocDedication,
    DocEndnote,
    DocEndnotes,
    DocEpigraph,
    DocEpilogue,
    DocErrata,
    DocExample,
    DocFootnote,
    DocForeword,
    DocGlossary,
    DocGlossref,
    DocIndex,
    DocIntroduction,
    DocNoteref,
    DocNotice,
    DocPagebreak,
    DocPagelist,
    DocPart,
    DocPreface,
    DocPrologue,
    DocPullquote,
    DocQna,
    DocSubtitle,
    DocTip,
    DocToc,
    Document,
    Emphasis,
    Feed,
    Figure,
    Form,
    Generic,
    GraphicsDocument,
    GraphicsObject,
    GraphicsSymbol,
    Grid,
    Gridcell,
    Group,
    Heading,
    Img,
    Insertion,
    Link,
    List,
    Listbox,
    Listitem,
    Log,
    Main,
    Mark,
    Marquee,
    Math,
    Menu,
    Menubar,
    Menuitem,
    Menuitemcheckbox,
    Menuitemradio,
    Meter,
    Navigation,
    None,
    Note,
    Option,
    Paragraph,
    Presentation,
    Progressbar,
    Radio,
    Radiogroup,
    Region,
    Row,
    Rowgroup,
    Rowheader,
    Scrollbar,
    Search,
    Searchbox,
    Separator,
    Slider,
    Spinbutton,
    Status,
    Strong,
    Subscript,
    Superscript,
    Switch,
    Tab,
    Table,
    Tablist,
    Tabpanel,
    Term,
    Textbox,
    Time,
    Timer,
    Toolbar,
    Tooltip,
    Tree,
    Treegrid,
    Treeitem,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaRoleDefinitionKey {
    Alert,
    Alertdialog,
    Application,
    Article,
    Banner,
    Blockquote,
    Button,
    Caption,
    Cell,
    Checkbox,
    Code,
    Columnheader,
    Combobox,
    Command,
    Complementary,
    Composite,
    Contentinfo,
    Definition,
    Deletion,
    Dialog,
    Directory,
    DocAbstract,
    DocAcknowledgments,
    DocAfterword,
    DocAppendix,
    DocBacklink,
    DocBiblioentry,
    DocBibliography,
    DocBiblioref,
    DocChapter,
    DocColophon,
    DocConclusion,
    DocCover,
    DocCredit,
    DocCredits,
    DocDedication,
    DocEndnote,
    DocEndnotes,
    DocEpigraph,
    DocEpilogue,
    DocErrata,
    DocExample,
    DocFootnote,
    DocForeword,
    DocGlossary,
    DocGlossref,
    DocIndex,
    DocIntroduction,
    DocNoteref,
    DocNotice,
    DocPagebreak,
    DocPageheader,
    DocPagefooter,
    DocPagelist,
    DocPart,
    DocPreface,
    DocPrologue,
    DocPullquote,
    DocQna,
    DocSubtitle,
    DocTip,
    DocToc,
    Document,
    Emphasis,
    Feed,
    Figure,
    Form,
    Generic,
    GraphicsDocument,
    GraphicsObject,
    GraphicsSymbol,
    Grid,
    Gridcell,
    Group,
    Heading,
    Img,
    Input,
    Insertion,
    Landmark,
    Link,
    List,
    Listbox,
    Listitem,
    Log,
    Main,
    Mark,
    Marquee,
    Math,
    Menu,
    Menubar,
    Menuitem,
    Menuitemcheckbox,
    Menuitemradio,
    Meter,
    Navigation,
    None,
    Note,
    Option,
    Paragraph,
    Presentation,
    Progressbar,
    Radio,
    Radiogroup,
    Range,
    Region,
    Roletype,
    Row,
    Rowgroup,
    Rowheader,
    Scrollbar,
    Search,
    Searchbox,
    Section,
    Sectionhead,
    Select,
    Separator,
    Slider,
    Spinbutton,
    Status,
    Strong,
    Structure,
    Subscript,
    Superscript,
    Switch,
    Tab,
    Table,
    Tablist,
    Tabpanel,
    Term,
    Textbox,
    Time,
    Timer,
    Toolbar,
    Tooltip,
    Tree,
    Treegrid,
    Treeitem,
    Widget,
    Window,
}

impl From<AriaAbstractRole> for AriaRoleDefinitionKey {
    fn from(value: AriaAbstractRole) -> Self {
        match value {
            AriaAbstractRole::Command => AriaRoleDefinitionKey::Command,
            AriaAbstractRole::Composite => AriaRoleDefinitionKey::Composite,
            AriaAbstractRole::Input => AriaRoleDefinitionKey::Input,
            AriaAbstractRole::Landmark => AriaRoleDefinitionKey::Landmark,
            AriaAbstractRole::Range => AriaRoleDefinitionKey::Range,
            AriaAbstractRole::Roletype => AriaRoleDefinitionKey::Roletype,
            AriaAbstractRole::Section => AriaRoleDefinitionKey::Section,
            AriaAbstractRole::Sectionhead => AriaRoleDefinitionKey::Sectionhead,
            AriaAbstractRole::Select => AriaRoleDefinitionKey::Select,
            AriaAbstractRole::Structure => AriaRoleDefinitionKey::Structure,
            AriaAbstractRole::Widget => AriaRoleDefinitionKey::Widget,
            AriaAbstractRole::Window => AriaRoleDefinitionKey::Window,
        }
    }
}

impl From<AriaRole> for AriaRoleDefinitionKey {
    fn from(value: AriaRole) -> Self {
        match value {
            AriaRole::Alert => AriaRoleDefinitionKey::Alert,
            AriaRole::Alertdialog => AriaRoleDefinitionKey::Alertdialog,
            AriaRole::Application => AriaRoleDefinitionKey::Application,
            AriaRole::Article => AriaRoleDefinitionKey::Article,
            AriaRole::Banner => AriaRoleDefinitionKey::Banner,
            AriaRole::Blockquote => AriaRoleDefinitionKey::Blockquote,
            AriaRole::Button => AriaRoleDefinitionKey::Button,
            AriaRole::Caption => AriaRoleDefinitionKey::Caption,
            AriaRole::Cell => AriaRoleDefinitionKey::Cell,
            AriaRole::Checkbox => AriaRoleDefinitionKey::Checkbox,
            AriaRole::Code => AriaRoleDefinitionKey::Code,
            AriaRole::Columnheader => AriaRoleDefinitionKey::Columnheader,
            AriaRole::Combobox => AriaRoleDefinitionKey::Combobox,
            AriaRole::Complementary => AriaRoleDefinitionKey::Complementary,
            AriaRole::Contentinfo => AriaRoleDefinitionKey::Contentinfo,
            AriaRole::Definition => AriaRoleDefinitionKey::Definition,
            AriaRole::Deletion => AriaRoleDefinitionKey::Deletion,
            AriaRole::Dialog => AriaRoleDefinitionKey::Dialog,
            AriaRole::Directory => AriaRoleDefinitionKey::Directory,
            AriaRole::DocAbstract => AriaRoleDefinitionKey::DocAbstract,
            AriaRole::DocAcknowledgments => AriaRoleDefinitionKey::DocAcknowledgments,
            AriaRole::DocAfterword => AriaRoleDefinitionKey::DocAfterword,
            AriaRole::DocAppendix => AriaRoleDefinitionKey::DocAppendix,
            AriaRole::DocBacklink => AriaRoleDefinitionKey::DocBacklink,
            AriaRole::DocBiblioentry => AriaRoleDefinitionKey::DocBiblioentry,
            AriaRole::DocBibliography => AriaRoleDefinitionKey::DocBibliography,
            AriaRole::DocBiblioref => AriaRoleDefinitionKey::DocBiblioref,
            AriaRole::DocChapter => AriaRoleDefinitionKey::DocChapter,
            AriaRole::DocColophon => AriaRoleDefinitionKey::DocColophon,
            AriaRole::DocConclusion => AriaRoleDefinitionKey::DocConclusion,
            AriaRole::DocCover => AriaRoleDefinitionKey::DocCover,
            AriaRole::DocCredit => AriaRoleDefinitionKey::DocCredit,
            AriaRole::DocCredits => AriaRoleDefinitionKey::DocCredits,
            AriaRole::DocDedication => AriaRoleDefinitionKey::DocDedication,
            AriaRole::DocEndnote => AriaRoleDefinitionKey::DocEndnote,
            AriaRole::DocEndnotes => AriaRoleDefinitionKey::DocEndnotes,
            AriaRole::DocEpigraph => AriaRoleDefinitionKey::DocEpigraph,
            AriaRole::DocEpilogue => AriaRoleDefinitionKey::DocEpilogue,
            AriaRole::DocErrata => AriaRoleDefinitionKey::DocErrata,
            AriaRole::DocExample => AriaRoleDefinitionKey::DocExample,
            AriaRole::DocFootnote => AriaRoleDefinitionKey::DocFootnote,
            AriaRole::DocForeword => AriaRoleDefinitionKey::DocForeword,
            AriaRole::DocGlossary => AriaRoleDefinitionKey::DocGlossary,
            AriaRole::DocGlossref => AriaRoleDefinitionKey::DocGlossref,
            AriaRole::DocIndex => AriaRoleDefinitionKey::DocIndex,
            AriaRole::DocIntroduction => AriaRoleDefinitionKey::DocIntroduction,
            AriaRole::DocNoteref => AriaRoleDefinitionKey::DocNoteref,
            AriaRole::DocNotice => AriaRoleDefinitionKey::DocNotice,
            AriaRole::DocPagebreak => AriaRoleDefinitionKey::DocPagebreak,
            AriaRole::DocPagelist => AriaRoleDefinitionKey::DocPagelist,
            AriaRole::DocPart => AriaRoleDefinitionKey::DocPart,
            AriaRole::DocPreface => AriaRoleDefinitionKey::DocPreface,
            AriaRole::DocPrologue => AriaRoleDefinitionKey::DocPrologue,
            AriaRole::DocPullquote => AriaRoleDefinitionKey::DocPullquote,
            AriaRole::DocQna => AriaRoleDefinitionKey::DocQna,
            AriaRole::DocSubtitle => AriaRoleDefinitionKey::DocSubtitle,
            AriaRole::DocTip => AriaRoleDefinitionKey::DocTip,
            AriaRole::DocToc => AriaRoleDefinitionKey::DocToc,
            AriaRole::Document => AriaRoleDefinitionKey::Document,
            AriaRole::Emphasis => AriaRoleDefinitionKey::Emphasis,
            AriaRole::Feed => AriaRoleDefinitionKey::Feed,
            AriaRole::Figure => AriaRoleDefinitionKey::Figure,
            AriaRole::Form => AriaRoleDefinitionKey::Form,
            AriaRole::Generic => AriaRoleDefinitionKey::Generic,
            AriaRole::GraphicsDocument => AriaRoleDefinitionKey::GraphicsDocument,
            AriaRole::GraphicsObject => AriaRoleDefinitionKey::GraphicsObject,
            AriaRole::GraphicsSymbol => AriaRoleDefinitionKey::GraphicsSymbol,
            AriaRole::Grid => AriaRoleDefinitionKey::Grid,
            AriaRole::Gridcell => AriaRoleDefinitionKey::Gridcell,
            AriaRole::Group => AriaRoleDefinitionKey::Group,
            AriaRole::Heading => AriaRoleDefinitionKey::Heading,
            AriaRole::Img => AriaRoleDefinitionKey::Img,
            AriaRole::Insertion => AriaRoleDefinitionKey::Insertion,
            AriaRole::Link => AriaRoleDefinitionKey::Link,
            AriaRole::List => AriaRoleDefinitionKey::List,
            AriaRole::Listbox => AriaRoleDefinitionKey::Listbox,
            AriaRole::Listitem => AriaRoleDefinitionKey::Listitem,
            AriaRole::Log => AriaRoleDefinitionKey::Log,
            AriaRole::Main => AriaRoleDefinitionKey::Main,
            AriaRole::Mark => AriaRoleDefinitionKey::Mark,
            AriaRole::Marquee => AriaRoleDefinitionKey::Marquee,
            AriaRole::Math => AriaRoleDefinitionKey::Math,
            AriaRole::Menu => AriaRoleDefinitionKey::Menu,
            AriaRole::Menubar => AriaRoleDefinitionKey::Menubar,
            AriaRole::Menuitem => AriaRoleDefinitionKey::Menuitem,
            AriaRole::Menuitemcheckbox => AriaRoleDefinitionKey::Menuitemcheckbox,
            AriaRole::Menuitemradio => AriaRoleDefinitionKey::Menuitemradio,
            AriaRole::Meter => AriaRoleDefinitionKey::Meter,
            AriaRole::Navigation => AriaRoleDefinitionKey::Navigation,
            AriaRole::None => AriaRoleDefinitionKey::None,
            AriaRole::Note => AriaRoleDefinitionKey::Note,
            AriaRole::Option => AriaRoleDefinitionKey::Option,
            AriaRole::Paragraph => AriaRoleDefinitionKey::Paragraph,
            AriaRole::Presentation => AriaRoleDefinitionKey::Presentation,
            AriaRole::Progressbar => AriaRoleDefinitionKey::Progressbar,
            AriaRole::Radio => AriaRoleDefinitionKey::Radio,
            AriaRole::Radiogroup => AriaRoleDefinitionKey::Radiogroup,
            AriaRole::Region => AriaRoleDefinitionKey::Region,
            AriaRole::Row => AriaRoleDefinitionKey::Row,
            AriaRole::Rowgroup => AriaRoleDefinitionKey::Rowgroup,
            AriaRole::Rowheader => AriaRoleDefinitionKey::Rowheader,
            AriaRole::Scrollbar => AriaRoleDefinitionKey::Scrollbar,
            AriaRole::Search => AriaRoleDefinitionKey::Search,
            AriaRole::Searchbox => AriaRoleDefinitionKey::Searchbox,
            AriaRole::Separator => AriaRoleDefinitionKey::Separator,
            AriaRole::Slider => AriaRoleDefinitionKey::Slider,
            AriaRole::Spinbutton => AriaRoleDefinitionKey::Spinbutton,
            AriaRole::Status => AriaRoleDefinitionKey::Status,
            AriaRole::Strong => AriaRoleDefinitionKey::Strong,
            AriaRole::Subscript => AriaRoleDefinitionKey::Subscript,
            AriaRole::Superscript => AriaRoleDefinitionKey::Superscript,
            AriaRole::Switch => AriaRoleDefinitionKey::Switch,
            AriaRole::Tab => AriaRoleDefinitionKey::Tab,
            AriaRole::Table => AriaRoleDefinitionKey::Table,
            AriaRole::Tablist => AriaRoleDefinitionKey::Tablist,
            AriaRole::Tabpanel => AriaRoleDefinitionKey::Tabpanel,
            AriaRole::Term => AriaRoleDefinitionKey::Term,
            AriaRole::Textbox => AriaRoleDefinitionKey::Textbox,
            AriaRole::Time => AriaRoleDefinitionKey::Time,
            AriaRole::Timer => AriaRoleDefinitionKey::Timer,
            AriaRole::Toolbar => AriaRoleDefinitionKey::Toolbar,
            AriaRole::Tooltip => AriaRoleDefinitionKey::Tooltip,
            AriaRole::Tree => AriaRoleDefinitionKey::Tree,
            AriaRole::Treegrid => AriaRoleDefinitionKey::Treegrid,
            AriaRole::Treeitem => AriaRoleDefinitionKey::Treeitem,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaNameFromSource {
    Author,
    Contents,
    Prohibited,
}

#[derive(Clone)]
pub struct AriaRoleDefinition {
    pub r#abstract: bool,
    pub accessible_name_required: bool,
    pub base_concepts: Vec<AriaRoleRelation>,
    pub children_presentational: bool,
    pub name_from: Vec<AriaNameFromSource>,
    pub prohibited_props: Vec<AriaProperty>,
    pub props: AriaPropertyMap,
    pub related_concepts: Vec<AriaRoleRelation>,
    pub require_context_role: Vec<AriaRole>,
    pub required_context_role: Vec<AriaRole>,
    pub required_owned_elements: Vec<Vec<String>>,
    pub required_props: AriaPropertyMap,
    pub super_class: Vec<Vec<AriaRoleDefinitionSuperClass>>,
}

#[derive(Clone)]
pub enum AriaRoleDefinitionSuperClass {
    AbstractRole(AriaAbstractRole),
    Role(AriaRole),
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaState {
    AriaBusy,
    AriaChecked,
    AriaDisabled,
    AriaExpanded,
    AriaGrabbed,
    AriaHidden,
    AriaInvalid,
    AriaPressed,
    AriaSelected,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaProperty {
    AriaActivedescendant,
    AriaAtomic,
    AriaAutocomplete,
    AriaBraillelabel,
    AriaBrailleroledescription,
    AriaBusy,
    AriaChecked,
    AriaColcount,
    AriaColindex,
    AriaColspan,
    AriaControls,
    AriaCurrent,
    AriaDescribedby,
    AriaDescription,
    AriaDetails,
    AriaDisabled,
    AriaDropeffect,
    AriaErrormessage,
    AriaExpanded,
    AriaFlowto,
    AriaGrabbed,
    AriaHaspopup,
    AriaHidden,
    AriaInvalid,
    AriaKeyshortcuts,
    AriaLabel,
    AriaLabelledby,
    AriaLevel,
    AriaLive,
    AriaModal,
    AriaMultiline,
    AriaMultiselectable,
    AriaOrientation,
    AriaOwns,
    AriaPlaceholder,
    AriaPosinset,
    AriaPressed,
    AriaReadonly,
    AriaRelevant,
    AriaRequired,
    AriaRoledescription,
    AriaRowcount,
    AriaRowindex,
    AriaRowspan,
    AriaSelected,
    AriaSetsize,
    AriaSort,
    AriaValuemax,
    AriaValuemin,
    AriaValuenow,
    AriaValuetext,
}

pub type AriaPropertyMap = HashMap<AriaProperty, Option<String>>;

#[derive(Clone)]
pub struct AriaPropertyDefinition {
    pub r#type: AriaPropertyDefinitionType,
    pub values: Option<Vec<String>>,
    pub allow_undefined: Option<bool>,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaPropertyDefinitionType {
    String,
    Id,
    Idlist,
    Integer,
    Number,
    Boolean,
    Token,
    Tokenlist,
    Tristate,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaPropertyCurrent {
    Page,
    Step,
    Locatiom,
    Date,
    Time,
    True,
    False,
}

#[derive(Clone)]
pub struct AriaRoleRelation {
    pub module: Option<String>,
    pub concept: Option<AriaRoleRelationConcept>,
}

#[derive(Clone, Eq, Hash, PartialEq)]
pub struct AriaRoleRelationConcept {
    pub name: String,
    pub attributes: Option<Vec<AriaRoleRelationConceptAttribute>>,
    pub constraints: Option<Vec<AriaRoleRelationConceptConstraint>>,
}

#[derive(Clone, Eq, Hash, PartialEq)]
pub struct AriaRoleRelationConceptAttribute {
    pub name: String,
    pub value: Option<AriaRoleRelationConceptAttributeValue>,
    pub constraints: Option<Vec<AriaRoleRelationConceptAttributeConstraint>>,
}

#[derive(Clone, Eq, Hash, PartialEq)]
pub enum AriaRoleRelationConceptAttributeValue {
    String(String),
    Number(isize),
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaRoleRelationConceptAttributeConstraint {
    Undefined,
    Set,
    GreaterThanOne,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaRoleRelationConceptConstraint {
    ScopedToTheBodyElement,
    ScopedToTheMainElement,
    ScopedToASectioningRootElementOtherThanBody,
    ScopedToASectioningContentElement,
    DirectDescendantOfDocument,
    DirectDescendantOfOl,
    DirectDescendantOfUl,
    DirectDescendantOfMenu,
    DirectDescendantOfDetailsElementWithTheOpenAttributeDefined,
    AncestorTableElementHasTableRole,
    AncestorTableElementHasGridRole,
    AncestorTableElementHasTreegridRole,
    TheSizeAttributeValueIsGreaterThanOne,
    TheMultipleAttributeIsNotSetAndTheSizeAttributeDoesNotHaveAValueGreaterThanOne,
    TheListAttributeIsNotSet,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AriaQueryHtmlElement {
    A,
    Abbr,
    Acronym,
    Address,
    Applet,
    Area,
    Article,
    Aside,
    Audio,
    B,
    Base,
    Bdi,
    Bdo,
    Big,
    Blink,
    Blockquote,
    Body,
    Br,
    Button,
    Canvas,
    Caption,
    Center,
    Cite,
    Code,
    Col,
    Colgroup,
    Content,
    Data,
    Datalist,
    Dd,
    Del,
    Details,
    Dfn,
    Dialog,
    Dir,
    Div,
    Dl,
    Dt,
    Em,
    Embed,
    Fieldset,
    Figcaption,
    Figure,
    Font,
    Footer,
    Form,
    Frame,
    Frameset,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Head,
    Header,
    Hgroup,
    Hr,
    Html,
    I,
    Iframe,
    Img,
    Input,
    Ins,
    Kbd,
    Keygen,
    Label,
    Legend,
    Li,
    Link,
    Main,
    Map,
    Mark,
    Marquee,
    Menu,
    Menuitem,
    Meta,
    Meter,
    Nav,
    Noembed,
    Noscript,
    Object,
    Ol,
    Optgroup,
    Option,
    Output,
    P,
    Param,
    Picture,
    Pre,
    Progress,
    Q,
    Rp,
    Rt,
    Rtc,
    Ruby,
    S,
    Samp,
    Script,
    Section,
    Select,
    Small,
    Source,
    Spacer,
    Span,
    Strike,
    Strong,
    Style,
    Sub,
    Summary,
    Sup,
    Table,
    Tbody,
    Td,
    Textarea,
    Tfoot,
    Th,
    Thead,
    Time,
    Title,
    Tr,
    Track,
    Tt,
    U,
    Ul,
    Var,
    Video,
    Wbr,
    Xmp,
}

pub struct AriaDomDefinition {
    pub reserved: bool,
}
