[package]
name = "aria-hidden"
description = "Rust port of aria-hidden."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
once_cell = "1.19.0"
web-sys = { workspace = true, features = [
    "Document",
    "Element",
    "HtmlElement",
    "Node",
    "NodeList",
    "ShadowRoot",
] }
