[package]
name = "aria-query"
description = "Rust port of ARIA Query."
version = "0.0.3"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
