[package]
name = "aria-query"
description = "Rust port of aria-query."
version = "0.0.2"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
