[package]
name = "aria-query"
description = "Rust port of ARIA Query."
version = "0.0.6"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ordered_hash_map = "0.5.0"
