[package]
name = "dom-accessibility-api"
description = "Rust port of dom-accessibility-api."
version = "0.0.1"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
regex = "1.10.6"
web-sys = { workspace = true, features = [
    "Attr",
    "CssStyleDeclaration",
    "Document",
    "DocumentFragment",
    "Element",
    "HtmlCollection",
    "HtmlFieldSetElement",
    "HtmlInputElement",
    "HtmlLabelElement",
    "HtmlLegendElement",
    "HtmlOptGroupElement",
    "HtmlSelectElement",
    "HtmlSlotElement",
    "HtmlTableElement",
    "HtmlTableCaptionElement",
    "HtmlTextAreaElement",
    "Node",
    "SvgElement",
    "SvgTitleElement",
    "Window",
] }
