use std::{collections::HashMap, sync::LazyLock};

use crate::types::{
    AriaAbstractRole, AriaNameFromSource, AriaProperty, AriaRole, AriaRoleDefinition,
    AriaRoleDefinitionKey, AriaRoleDefinitionSuperClass, AriaRoleRelation, AriaRoleRelationConcept,
};

pub static ARIA_DPUB_ROLES: LazyLock<HashMap<AriaRoleDefinitionKey, AriaRoleDefinition>> =
    LazyLock::new(|| {
        HashMap::from([
            (
                AriaRoleDefinitionKey::DocAbstract,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "r#abstract vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocAcknowledgments,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "acknowledgments vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocAfterword,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "afterword vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocAppendix,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "appendix vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocBacklink,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author, AriaNameFromSource::Contents],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "referrer vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Widget),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Command),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Link),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocBiblioentry,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "EPUB biblioentry vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![AriaRole::DocBibliography],
                    required_context_role: vec![AriaRole::DocBibliography],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Listitem),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocBibliography,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "bibliography vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![vec!["doc-biblioentry".into()]],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocBiblioref,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author, AriaNameFromSource::Contents],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "biblioref vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Widget),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Command),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Link),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocChapter,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "chapter vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocColophon,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "colophon vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocConclusion,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "conclusion vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocCover,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "cover vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Img),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocCredit,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "credit vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocCredits,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "credits vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocDedication,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "dedication vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocEndnote,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "rearnote vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![AriaRole::DocEndnotes],
                    required_context_role: vec![AriaRole::DocEndnotes],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Listitem),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocEndnotes,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "rearnotes vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![vec!["doc-endnote".into()]],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocEpigraph,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "epigraph vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocEpilogue,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "epilogue vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocErrata,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "errata vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocExample,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocFootnote,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "footnote vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocForeword,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "foreword vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocGlossary,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "glossary vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![vec!["definition".into()], vec!["term".into()]],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocGlossref,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author, AriaNameFromSource::Contents],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "glossref vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Widget),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Command),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Link),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocIndex,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "index vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Navigation),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocIntroduction,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "introduction vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocNoteref,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author, AriaNameFromSource::Contents],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "noteref vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Widget),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Command),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Link),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocNotice,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "notice vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Note),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPagebreak,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: true,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "pagebreak vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Separator),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPagefooter,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Prohibited],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaBraillelabel, None),
                        (AriaProperty::AriaBrailleroledescription, None),
                        (AriaProperty::AriaDescription, None),
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPageheader,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Prohibited],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaBraillelabel, None),
                        (AriaProperty::AriaBrailleroledescription, None),
                        (AriaProperty::AriaDescription, None),
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPagelist,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "page-list vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Navigation),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPart,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: true,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "part vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPreface,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "preface vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPrologue,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "prologue vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocPullquote,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "pullquote vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![AriaRoleDefinitionSuperClass::Role(AriaRole::None)]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocQna,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "qna vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocSubtitle,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "subtitle vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Sectionhead),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocTip,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "help vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Note),
                    ]],
                },
            ),
            (
                AriaRoleDefinitionKey::DocToc,
                AriaRoleDefinition {
                    r#abstract: false,
                    accessible_name_required: false,
                    base_concepts: vec![],
                    children_presentational: false,
                    name_from: vec![AriaNameFromSource::Author],
                    prohibited_props: vec![],
                    props: HashMap::from([
                        (AriaProperty::AriaDisabled, None),
                        (AriaProperty::AriaErrormessage, None),
                        (AriaProperty::AriaExpanded, None),
                        (AriaProperty::AriaHaspopup, None),
                        (AriaProperty::AriaInvalid, None),
                    ]),
                    related_concepts: vec![AriaRoleRelation {
                        concept: Some(AriaRoleRelationConcept {
                            name: "toc vec![EPUB-SSV]".into(),
                            attributes: None,
                            constraints: None,
                        }),
                        module: Some("EPUB".into()),
                    }],
                    require_context_role: vec![],
                    required_context_role: vec![],
                    required_owned_elements: vec![],
                    required_props: HashMap::new(),
                    super_class: vec![vec![
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Roletype),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Structure),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Section),
                        AriaRoleDefinitionSuperClass::AbstractRole(AriaAbstractRole::Landmark),
                        AriaRoleDefinitionSuperClass::Role(AriaRole::Navigation),
                    ]],
                },
            ),
        ])
    });
